## cert-manager configuration
#
## https://github.com/jetstack/cert-manager/blob/master/docs/user-guides/deploying.md#step-1---deploying-cert-manager
# git clone https://github.com/jetstack/cert-manager --branch v0.2.3 --single-branch
# helm install --name cert-manager --namespace kube-system cert-manager/contrib/charts/cert-manager -f cert-manager-config.yml
#
## TODO: Use stable/cert-manager when it's updated:
# helm install stable/cert-manager --version=0.2.X --name=cert-manager --namespace=default -f cert-manager-config.yml

ingressShim:
  extraArgs:
  - "--default-issuer-name=letsencrypt-prod"
  - "--default-issuer-kind=ClusterIssuer"
