## Cluster issuer for automatic lets encrypt certificates
## Install cert-manager first, then create this resource:
# kubectl create -f clusterissuer.yaml
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: sysadmin@openmicroscopy.org
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
